service: AWS-Monitoring-Mock
app: server-app

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 30
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

plugins:
  - serverless-offline
  - postgresql-easy

functions:

  getQuery:
    handler: handler.getQuery
    events:
      - http:
          path: query/{query_name}
          method: get
          cors: true

  getSingleCountOrDrilldown:
    handler: handler.getSingleCountOrDrilldown
    events:
      - http:
          path: count-drilldown/{query_name}
          method: get
          cors: true

  getScenarios:
    handler: handler.getScenarios
    events:
      - http:
          path: scenarios
          method: get
          cors: true

  createUpdateQuery:
    handler: handler.createUpdateQuery
    events:
      - http:
          path: query
          method: post
          cors: true

  generateSummary:
    handler: handler.generateSummary
    events:
      - http:
          path: summary
          method: get
          cors: true
  
  getLatestData:
    handler: handler.getLatestData
    events:
      - http:
          path: getlatest
          method: get
          cors: true
