service: AWS-Monitoring-Mock
app: server-app



provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 30
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

plugins:
  - serverless-offline
  - postgresql-easy

functions:

  getSummary:
    handler: handler.getSummary
    events:
      - http:
          path: query/{query_name}
          method: get
          cors: true

  getScenarios:
    handler: handler.getScenarios
    events:
      - http:
          path: scenarios
          method: get
          cors: true

  getStats:
    handler: handler.getStats
    events:
      - http:
          path: stats/{scenario_name}
          method: get
          cors: true

  createUpdateQuery:
    handler: handler.createUpdateQuery
    events:
      - http:
          path: query
          method: post
          cors: true

  generateSummary:
    handler: handler.generateSummary
    events:
      - http:
          path: summary
          method: get
          cors: true

  # getTodo:
  #   handler: handler.getTodo
  #   events:
  #    - http:
  #        path: todo/{id}
  #        method: get
  #        cors: true
          
  # getAllTodos:
  #   handler: handler.getAllTodos
  #   events:
  #    - http:
  #        path: todo
  #        method: get
  #        cors: true

  # createTodo:
  #   handler: handler.createTodo
  #   events:
  #     - http:
  #         path: todo
  #         method: post
  #         cors: true
              
  # updateTodo:
  #   handler: handler.updateTodo
  #   events:
  #     - http:
  #         path: todo/{id}
  #         method: put
  #         cors: true